### ISSUE TITLE
[FEAT] RecordView 구현 

### ISSUE THREAD

**Issue by lenamin** [lenamin/Music-Catcher#1]
## 💡 Issue

RecordView를 구현합니다 

## 📝  todo
- [x] RecordButton 생성 
- [x] 버튼에 gradient 색상 적용하기 
- [x] RecordButton 누르면 Recording 화면으로 넘어가도록 구현 
- [x] 탭바 구현 (Record, Files, Favorites, Setting) 
- [x] 커스텀 컬러 등록하기 

## 📸 Screenshot

<img width="279" alt="Screenshot 2023-04-06 at 6 40 49 PM" src="https://user-images.githubusercontent.com/99120199/230338499-a690f892-7d36-4dcf-b23d-c16fafcbed9f.png">
