### ISSUE TITLE
[FEAT] AudioVisualizer, RecordingView 구현 

### ISSUE THREAD

**Issue by lenamin** [lenamin/Music-Catcher#2]
## 💡 Issue

녹음 중 화면과 audio visualizer 를 구현합니다 

## 📝  todo
- [x] SoundVisualizer 구현 
- [x] 녹음 시간 레이블 구현 (녹음시간이 실시간 카운트되는 기능 구현) 
- [x] 재생, 일시정지, 정지 버튼 구현 
- [x] 녹음 기능 구현 

## 📸 Screenshot

<img width="165" alt="Screenshot 2023-04-10 at 3 18 05 PM" src="https://user-images.githubusercontent.com/99120199/230839354-e2cc1b66-b17f-4aeb-8a9b-7544bb633ec7.png">
