### ISSUE TITLE
[FEAT] FileGroup, FileList, Playlist View 구현 

### ISSUE THREAD

**Issue by lenamin** [lenamin/Music-Catcher#4]
## 💡 Issue

FileGroup, FileList, Playlist View 구현 

## 📝  todo
- [x] FileGroup -> 테이블 뷰 구현 (그루핑) / 검색 기능 구현 
- [x] FileList -> 테이블 뷰 구현 (제목, 태그) / 검색 기능 구현 
- [x] PlayList -> UI구현 / 녹음한 파일과 연동되도록 구현 
- [x] FileManager 구현 -> 녹음한 데이터가 FileGroup, FileList에 올라오도록 구현 

## 📸 Screenshot

<img width="250" alt="Screenshot 2023-04-30 at 11 42 25 AM" src="https://user-images.githubusercontent.com/99120199/235333005-5177335d-c7c0-4020-bbe6-44441f015154.png">
<img width="250" alt="Screenshot 2023-04-30 at 11 42 40 AM" src="https://user-images.githubusercontent.com/99120199/235333009-df6036ee-f4a9-4725-b9a2-e4dadfb27824.png">
