### ISSUE TITLE
[FEAT] 녹음 및 음원 데이터 저장, 재생 기능 구현 

### ISSUE THREAD

**Issue by lenamin** [lenamin/Music-Catcher#6]
## 💡 Issue

- [x] 데이터와 UI를 연결합니다. 

## 📝  todo
- [x] `startRecording()` 메서드를 실행하고, `stop()` 하면 fileListView에 update되는 기능 구현 
- [ ] fileGroupView `+` 버튼으로 새로운 폴더 생성 기능 구현 
- [ ] fileGrouptView `edit` 버튼으로 파일 목록 및 파일 수정 기능 구현 (+ 삭제 포함)
