### ISSUE TITLE
[FEAT] CoreData, CloudKit DB 작업 

### ISSUE THREAD

**Issue by lenamin** [lenamin/Music-Catcher#8]
## 💡 Issue

filemanager에 저장된 오디오들의 데이터를 로컬 기기에 저장하고, 이를 기기간 동기화 및 백업을 할 수 있는 iCloud 동기화 기능 구현 

## 📝  todo
- [x] AudioModel 데이터 CRUD 기능 구현 
- [x] CoreData Model 구현 
- [ ] CloudKit Model 구현
